obj-$(CONFIG_CPUFREQ_SCPI) += cpufreq_if.o
obj-$(CONFIG_CPUFREQ_SCPI) += scpi_cpufreq.o
obj-$(CONFIG_CPUFREQ_SCPI) += arm_scpi.o
obj-$(CONFIG_CPUFREQ_SCPI) += mailbox.o
obj-$(CONFIG_CPUFREQ_SCPI) += arm-smc-mailbox.o
obj-$(CONFIG_CPUFREQ_SCPI) += rcar_gen3_thermal.o
obj-$(CONFIG_CPUFREQ_IMX) += imx_sc_cpufreq.o
obj-$(CONFIG_CPUFREQ_IMX) += imx_sc_thermal.o
